#!/bin/bash

#ENSEMBLE_REMOTE_UNIT

    #change_unit  = subprocess.check_output(['relation-list']).strip().split("\n")[0]


#lastrun_path= "/var/lib/ensemble/${db_name}.${db_user}.lastrun"

#if database_already_exists(database_name):
#    print "database exists, assuming configuration has happened already"
#    sys.exit(0)


database=${ENSEMBLE_REMOTE_UNIT///*}
user=${ENSEMBLE_REMOTE_UNIT///*}
host=`hostname -f`
password=`pwgen -s 16`

password_path= "/var/lib/ensemble/${database}.${user}.password"

sudo -su postgres psql -c"create user '${user}' with superuser password '${password}'"
sudo -su postgres psql -c"create database ${database} owner ${user}" 
sudo -su postgres psql -c"grant all privileges on database ${database} to ${user}"

relation-set database=${database} user=${user} password=${password} host=${host}

