#!/bin/bash

[[ -f "$(dirname $0)/common.sh" ]] && source "$(dirname $0)/common.sh"

remote_host=`relation-get ip`
if [ -n "$remote_host" ]; then
  juju-log -l WARNING "remote unit $JUJU_REMOTE_UNIT uses deprecated 'ip=' component of interface."
else
  remote_host=`relation-get private-address`
fi
if [ -z "$remote_host" ]; then   #if [ -z $JUJU_REMOTE_UNIT ]; then
  juju-log "remote host not set yet"
  exit 0
fi

grant_host_access() {
  echo "host $(get_database_name) ${user} ${remote_host} md5" >> /etc/postgresql/*/main/pg_hba.conf
}
host_can_access() {
  grep -q "$(get_database_name).*${user}.*${remote_host}" /etc/postgresql/*/main/pg_hba.conf
}
host_can_access || grant_host_access

juju-log "starting postgresql"
service postgresql restart || service postgresql start

