#!/bin/bash


ensemble-log "Relationship with ${database} broken."

revoke_access() {
  sudo -su postgres psql -c"revoke all privileges on database ${database} from ${user};"
}
revoke_access
#    echo "revoked privileges for ${user} on database ${database}"
#    echo "revoking failed"
