#!/bin/bash

remote_host=`relation-get ip`
if [ -z "$remote_host" ]; then   #if [ -z $ENSEMBLE_REMOTE_UNIT ]; then
  ensemble-log "remote host not set yet"
  exit 0
fi

database=${ENSEMBLE_REMOTE_UNIT///*}
user=${ENSEMBLE_REMOTE_UNIT///*}
host=`hostname -f`

service_password_file="/var/lib/ensemble/${database}.${user}.password"
create_password() {
  password=`pwgen -s 16`
  echo ${password} > ${service_password_file}
}
has_password() {
  [ -f ${service_password_file} ] && password=`cat ${service_password_file}`
}
has_password || create_password

create_database() {
  sudo -su postgres psql -c"create user ${user} with superuser password '${password}'"
  sudo -su postgres psql -c"create database ${database} owner ${user}" 
  sudo -su postgres psql -c"grant all privileges on database ${database} to ${user}"
}
has_database() {
  sudo -su postgres psql -c"select datname from pg_database;" | grep -q ${database}
}
has_database || create_database

grant_host_access() {
  echo "host ${database} ${user} ${remote_host}/0 md5" >> /etc/postgresql/*/main/pg_hba.conf
}
host_can_access() {
  grep -q ${remote_host} /etc/postgresql/*/main/pg_hba.conf
}
host_can_access || grant_host_access

ensemble-log "starting postgresql"
service postgresql restart || service postgresql start

relation-set database=${database} user=${user} password=${password} host=${host} database_type='postgresql'

